import pc10jt from '../images/pc10jt.png';
import RogZepfiruz from '../images/ROG Zepfiruz.png';
import LogitechG305 from '../images/Logitech G305.png';
import HyperXHHSS1C from '../images/HyperX HHSS1C.png';
import StrixG16 from '../images/ASUS ROG Strix G16.png';
import Legion5 from '../images/Legion5.png';
import RazerOrnata from '../images/RazerOrnata.png';
import Pc20jt2 from '../images/Pc20jt2.png';
export const data = [
  {
    imageSrc: `${pc10jt}`,
    name: 'Rakitan 10jt',
    company: 'Chicken Main Course',
    category: 'PC Rakitan',
    price: 250000,
    rating: 5,
    reviews: 87,
    shipping: false,
    stock: 10,
    colors: [],
    description: 'testing satu dua tiga',
  },
  {
    imageSrc: `${RogZepfiruz}`,
    name: 'ROG Zepfiruz',
    company: 'Fried Mexican Beef',
    category: 'Laptop',
    price: 175000,
    rating: 4,
    reviews: 34,
    shipping: true,
    stock: 10,
    colors: [],
    description: 'testing satu dua tiga',
  },
  {
    imageSrc: `${LogitechG305}`,
    name: 'Logitech G305',
    company: 'Chilli Crispy Nachos',
    category: 'Gaming Acc',
    price: 550000,
    rating: 3,
    reviews: 26,
    shipping: false,
    stock: 10,
    colors: [],
    description: 'testing satu dua tiga',
  },
  {
    imageSrc: `${Pc20jt2}`,
    name: 'Rakitan 20jt',
    company: 'Mexican Chilli',
    category: 'PC Rakitan',
    price: 350000,
    rating: 4,
    reviews: 95,
    shipping: true,
    stock: 10,
    colors: [],
    description: 'testing satu dua tiga',
  },
  {
    imageSrc: `${HyperXHHSS1C}`,
    name: 'HyperX HHSS1C',
    company: 'Deepfried Chicken',
    category: 'Gaming Acc',
    price: 120000,
    rating: 5,
    reviews: 61,
    shipping: false,
    stock: 10,
    colors: [],
    description: 'testing satu dua tiga',
  },
  {
    imageSrc: `${StrixG16}`,
    name: 'ASUS ROG Strix G16 ',
    company: 'Hamburger & Fries',
    category: 'Laptop',
    price: 250000,
    rating: 4,
    reviews: 89,
    shipping: true,
    stock: 10,
    colors: [],
    description: 'testing satu dua tiga',
  },
  {
    imageSrc: `${Legion5}`,
    name: 'Lenovo Legion 5',
    company: 'Crispy Soyabeans',
    category: 'Laptop',
    price: 150000,
    rating: 4,
    reviews: 12,
    shipping: false,
    stock: 10,
    colors: [],
    description: 'testing satu dua tiga',
  },
  {
    imageSrc: `${RazerOrnata}`,
    name: 'Razer Ornata V3 Mecha',
    company: 'Roasted Chicken & Egg',
    category: 'Gaming Acc',
    price: 450000,
    rating: 3,
    reviews: 19,
    shipping: false,
    stock: 10,
    colors: [],
    description: 'testing satu dua tiga',
  },
];
